# Generated by Django 5.0.5 on 2024-05-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taskapi',
        ),
    ]
